import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  homeButton: {
    flex: 1,
    backgroundColor: "#1D91AD",
    alignItems: "center",
    justifyContent: "center",
    borderColor: "#ffb800",
    borderWidth: 8,
    borderRadius: 15,
  },
  linksText: {
    textAlign: "center",
    fontSize: 25,
    fontFamily: 'Bangers_400Regular',
    color: "#ffb800",
  },
  linksBox1: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: "#1D91AD",
    alignItems: "center",
    justifyContent: "center",
    borderColor: "#ffb800",
    borderWidth: 15,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.29,
    shadowRadius: 4.65,
    elevation: 7,
  },
  linksBox2: {
    flex: 1,
    backgroundColor: "#1D91AD",
    alignItems: "center",
    justifyContent: "center",
    borderColor: "#ffb800",
    borderWidth: 15,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.29,
    shadowRadius: 4.65,
    elevation: 7,
  },
  linksBox3: {
    flex: 1,
    backgroundColor: "#1D91AD",
    alignItems: "center",
    justifyContent: "center",
    borderColor: "#ffb800",
    borderWidth: 15,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.29,
    shadowRadius: 4.65,
    elevation: 7,
  },
  linksBox4: {
    flex: 1,
    backgroundColor: "#1D91AD",
    alignItems: "center",
    justifyContent: "center",
    borderColor: "#ffb800",
    borderWidth: 15,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.29,
    shadowRadius: 4.65,
    elevation: 7,
  },
  input: {
    flex: 0.25,
    width: '40%',
    justifyContent: 'center',
    alignItems: 'center',
    fontFamily: 'Bangers_400Regular',
    fontSize: 25,
    color: "#1D91AD",
    paddingLeft: 30,
  },
  powered: {
    flex: 0.25,
    fontFamily: 'Bangers_400Regular',
    alignItems: 'center',
  },
  loginButton: {
    flex: 0.15,
    backgroundColor: '#1D91AD',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loginButtonText: {
    flex: 1,
    fontFamily: 'Bangers_400Regular',
    fontSize: 30,
    color: '#ffb800',
    textAlignVertical: 'center',
  },
  welcomeContainer: {
    flex: 1,
    backgroundColor: '#1D91AD',
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: '#ffb800',
    borderWidth: 15,
    elevation: 17,
  },
  welcomeText: {
    fontSize: 25,
    fontFamily: 'Bangers_400Regular',
    color: '#ffb800',
  },
  calendarContainer: {
    flex: 2,
    backgroundColor: '#1D91AD',
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: '#ffb800',
    borderWidth: 9,
    borderRadius: 15,
    elevation: 7,
  },
  calendarText: {
    fontSize: 70,
    fontFamily: 'Bangers_400Regular',
    color: '#ffb800',
  },
  actionButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#ffb800',
    padding: 10,
  },
  button: {
    width: '30%',
    padding: 10,
    backgroundColor: '#1D91AD',
    borderRadius: 15,
    margin: 5,
  },
  buttonText: {
    fontSize: 40,
    textAlign: 'center',
    fontFamily: 'Bangers_400Regular',
    color: '#ffb800',
  },
  poweredByContainer: {
    padding: 10,
    backgroundColor: '#ffb800',
  },
  poweredByText: {
    textAlign: 'center',
    fontFamily: 'Bangers_400Regular',
    color: '#1D91AD',
  },
  //
  container: {
    flex: 1,
    backgroundColor: '#ffb800',
    // alignItems: 'center',
    // justifyContent: 'center',
  },
  loginForm: {
    flex: 2,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  input2: {
    flex: 0.25,
    width: '100%',
    padding: 15,
    marginBottom: 10,
    backgroundColor: '#fff',
    borderColor: '#ddd',
    borderWidth: 1,
    borderRadius: 5,
    fontFamily: 'Bangers_400Regular',
  },
  loginButton2: {
    backgroundColor: '#1D91AD',
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 5,
    width: '100%',
    alignItems: 'center',
  },
  loginButtonText2: {
    color: '#ffb800',
    fontFamily: 'Bangers_400Regular',
    fontSize: 25,
  },
  errorText: {
    color: 'red',
    marginBottom: 10,
    textAlign: 'center',
  },
  //
  container2: {
    flex: 1,
    backgroundColor: '#ffb800',
  },
  linksRow: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  linkBox: {
    backgroundColor: '#1D91AD',
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    width: '40%',
    height: '70%',
  },
  linkText: {
    marginTop: 10,
    color: '#ffb800',
    fontFamily: 'Bangers_400Regular',
    fontSize: 20,
  },

});
